name: Deploy pharmacy showcase

on:
  push:
    paths:
      - pharmacy_showcase/**
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo -u anyuser -p ${{secrets.SCALEWAY_TOKEN}}
      - name: Docker build
        run: docker build -f Dockerfile  -t pharmacyshowcase:latest .
        working-directory: ./pharmacy_showcase
      - name: Docker tag
        run: docker tag pharmacyshowcase:latest rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo/pharmacyshowcase:latest
      - name: Docker push
        run: docker push rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo/pharmacyshowcase:latest
      - name: Deploy container
        run: curl -X POST -H "X-Auth-Token:${{secrets.SCALEWAY_TOKEN}}" "https://api.scaleway.com/functions/v1alpha2/regions/fr-par/containers/5d212918-9456-44f2-b459-2b5d30fe5972/deploy" -d "{}"
