name: Deploy production accounts service

on:
  push:
    paths:
      - services/accounts/**
      - .github/workflows/deploy_accounts_service_production.yaml
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo -u anyuser -p ${{secrets.SCALEWAY_TOKEN}}
      - name: Docker build
        run: docker build -f Dockerfile  -t productionas:latest .
        working-directory: ./services/accounts
      - name: Docker tag
        run: docker tag productionas:latest rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo/productionas:latest
      - name: Docker push
        run: docker push rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo/productionas:latest
      - name: Deploy container
        run: curl -X POST -H "X-Auth-Token:${{secrets.SCALEWAY_TOKEN}}" "https://api.scaleway.com/functions/v1alpha2/regions/fr-par/containers/0e3aa12e-6344-4606-8dcc-3154a656cb3f/deploy" -d "{}"
