name: Deploy pharmacy showcase

on:
  push:
    paths:
      - pharmacy_showcase/**
      - .github/workflows/deploy_showcase_production.yaml
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo -u anyuser -p ${{secrets.SCALEWAY_TOKEN}}
      - name: Docker build
        run: docker build -f Dockerfile  -t stagingps:latest .
        working-directory: ./pharmacy_showcase
      - name: Docker tag
        run: docker tag stagingps:latest rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo/productionps:latest
      - name: Docker push
        run: docker push rg.fr-par.scw.cloud/funcscwsantetisfmaxsfvo/productionps:latest
      - name: Deploy container
        run: curl -X POST -H "X-Auth-Token:${{secrets.SCALEWAY_TOKEN}}" "https://api.scaleway.com/functions/v1alpha2/regions/fr-par/containers/018a66ad-1ba0-4915-b4b9-e71fb7615365/deploy" -d "{}"
